#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

APP_PATH = File.expand_path('../../config/application', __FILE__)
require File.expand_path('../../config/boot', __FILE__)
require 'rails/commands'

User.create!({:email => "admin@123.com", :role => "admin", :password => "123456", :password_confirmation => "123456"})
User.create!({:email => "moderator@123.com", :role => "moderator", :password => "123456", :password_confirmation => "123456"})
User.create!({:email => "author@123.com", :role => "author", :password => "123456", :password_confirmation => "123456"})